# Generated by Django 5.2.5 on 2025-08-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent',
        ),
        migrations.AddField(
            model_name='order',
            name='paymob_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymob_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
